version: "2"
services:
    www:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql
        ports: 
            - "8002:3306"
        environment:
            MYSQL_DATABASE: forum_culinaire
            MYSQL_USER: user
            MYSQL_PASSWORD: mdp
            MYSQL_ROOT_PASSWORD: mdp
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./my.cnf:/etc/mysql/conf.d/z_my.cnf
            - persistent:/var/lib/mysql
        networks:
            - default
        restart: always
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: mdp
            MYSQL_ROOT_PASSWORD: mdp
volumes:
    persistent: